---
title: "Chetan Chawla"
about:
  template: jolla
  links:
    - icon: twitter
      text: Twitter
      href: https://twitter.com/ChetanChawla
    - icon: github
      text: Github
      href: https://github.com/csqr
    - icon: linkedin
      text: LinkedIn
      href: https://www.linkedin.com/in/chetanchawla
    - icon: googlescholar
      text: Google Scholar
      href: https://scholar.google.com/citations?user=Yt-84E4AAAAJ&hl=en&oi=ao
---

I am a teacher, researcher, and consultant of business strategy, and entrepreneurship. I have 10+ years of business consulting experience with clients ranging from Fortune 100 defense companies to technology startups. My professional, research, and teaching pursuits have been concentrated on high-technology (primarily software) ventures since the late 2000s.

My research focus spans capital providers (debt, equity, and non-traditional forms of financing), and technology startups -- primarily in the context of Web 3 and Artificial Intelligence technologies. In these contexts, I investigate issues related to trust, governance, and competitive dynamics using a diverse range of methodologies.

I am an [Associate Professor of Entrepreneurship](https://www.northcentralcollege.edu/profile/cchawla) at North Central College in Naperville, IL in the School of Business and Entrepreneurship. I primarily teach strategy, and entrepreneurship classes at North Central College.

The content of this website is a catalog of my evolving thinking about strategy, startups, science etc.\*.

\*Legal Disclaimer: The content on this site is purely a record of my personal interests/ experiments/ opinions/ speculations/, which are subject to updating. Nothing here constitutes investment/legal/professional advice. As always, [caveat lector](https://chetanchawla.com/post/caveat-lector/).

## Education

PhD in Strategic Management, 2015 \| UMASS, Amherst, MA

MBA in International Business, 2008 \| USC, Los Angeles, CA

B.A.(Hons) in English, 2003 \| Sri Aurobindo College, University of Delhi, India

## 
